GOOGLE_API_KEY : AIzaSyD2rAOoOrg0Y77V-FsxiExTigGSITKe0og

AWS_API_KEY: AKIAJQGDG6OSXOMKRPTQ
AWS_REGION: us-east-1
AWS_SECERT_KEY: wGCVXdTR/FqRuR6mecbhhAjy1gu8CmfUNctaX34r
BUCKET_NAME: parksmart-user-images